project_id = "bllwrehynktoboezwalw"

[functions.delete-users]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
